<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Harvest\Harvest.csproj" />
    <ProjectReference Include="..\..\..\..\src\Seamlineage.Hosting.InProc\Seamlineage.Hosting.InProc.csproj" />
  </ItemGroup>

</Project>
